### ISSUE TITLE
Changeset and setTag

### ISSUE THREAD

**Issue by PanierAvide** [pear/Services_Openstreetmap#128]
Hello,

I started using this library (1.0.0RC2), which is really helpful. I can't figure if there is a way yet to change changeset tags. I tried :

```
$osm = new Services_OpenStreetMap([...]);
$changeset = $osm->createChangeset();
$changeset->begin(...);
$changeset->setTag('host', '...');
...
$changeset->commit();
```

And defined tags are not applied. I also tried `$changeset->add($changeset);` to mimic other objects behaviour, but this causes an infinite loop. I'm not sure if setting custom tags on changesets is not permitted yet by the library, or if I missed how to use it.

By reading current code, I understand that most of changeset tags are hard-written in `begin` method. If this is not supported, one simple solution could be to add a `tags` parameter to this function and append custom tags to existing ones. One more complex solution could be to handle [PUT HTTP call on changesets](https://wiki.openstreetmap.org/wiki/API_v0.6#Update:_PUT_.2Fapi.2F0.6.2Fchangeset.2F.23id).

Best regards.

**Comment by sascha-hendel** [comment]
I need to add custom tags to the changeset, too.
Right now changeset tags are indeed hardcoded as PanierAvide mentioned. Implementation of a setTag method for changeset similar to item would be nice! @kenguest  do You still maintain this project? I could create a fork and try to do the implementation. Would You merge the fork if things working? (I only spent my time therefore if there is a chance that the result will go into the main fork)

**Comment by sascha-hendel** [comment]
Tested my fork with a setTag method for changeset now for a while. Seems to work.
Pull request (#214) created.

**Comment by kenguest** [comment]
Closing as pr #214 has addressed this, thanks to @sascha-hendel !!
