### ISSUE TITLE
Use https for openstreetmap.org servers

### ISSUE THREAD

**Issue by grischard** [pear/Services_Openstreetmap#18]
The nominatim geocoding service at nominatim.openstreetmap.org is available over https, and [will soon start redirecting all http requests to https](https://lists.openstreetmap.org/pipermail/geocoding/2018-January/001918.html).

Would it please be possible to make all nominatim requests over https?

Ideally, would it be possible to make all requests to openstreetmap.org over https?

**Comment by kenguest** [comment]
Hi @grischard - thank you for your suggestions which I have implemented and released in version v1.0.0RC1 just a few minutes ago. Greatly appreciated.
