### ISSUE TITLE
Disable verify ssl validation

### ISSUE THREAD

**Issue by erkinsergey** [pear/Services_Openstreetmap#32]
How can I prevent ssl from checking without changing the source code of the class Services_OpenStreetMap_Transport_HTTP? 

Now I was able to achieve this only by changing the code :
```
class Services_OpenStreetMap_Transport_HTTP
    implements Services_OpenStreetMap_Transport
{
...
 public function getResponse(
        $url,
        $method = HTTP_Request2::METHOD_GET,
        $user = null,
        $password = null,
        $body = null,
        array $post_data = null,
        array $headers = null
    ) {
        ...
        $request = $this->getRequest();
        $request->setUrl($url);
        $request->setMethod($method);
        $request->setAdapter($this->getConfig()->getValue('adapter'));

        // my insertion
        $request->setConfig('ssl_verify_peer', FALSE);
        $request->setConfig('ssl_verify_host', FALSE);
        // the end of my insertion
        ...
```

**Comment by kenguest** [comment]
hi - thanks for your feedback.

I might address this shortly by introducing a new option in the Config object - until then your change looks good.

Thanks again!

**Comment by kenguest** [comment]
hi @erkinsergey - I've committed some changes so that you should be able to do this now by setting the config for Services_OpenStreetMap instead of relying on your insertions.

...
$config = ['ssl_verify_peer' => false, 'ssl_verify_host' => false];
$osm = Services_OpenStreetMap($config);
...

I'll push a new release once I know this works as expected for you.

**Comment by erkinsergey** [comment]
Yes, that's exactly what I need!

**Comment by erkinsergey** [comment]
After testing, I changed the comment above.

**Comment by kenguest** [comment]
I've added some unit tests and found that changing the config values in either way, does seem to propagate the new values correctly:

**$config = ['ssl_verify_peer' => false, 'ssl_verify_host' => false];
$osm = new Services_OpenStreetMap($config);**
shows both turned off

**$osm = new Services_OpenStreetMap();
$osm->getConfig()->setValue('ssl_verify_host', 1);
$osm->getConfig()->setValue('ssl_verify_peer', 0);**
shows verify_host on, but verify_peer off.

I checked these, like you, by adding print_r calls into Services/OpenStreetMap/Transport/HTTP.php after the setConfig calls.

Maybe you're not looking at the recent-most portion of your log file?

**Comment by erkinsergey** [comment]
Unfortunately, while we do not understand each other. I'll try to explain again. Sorry for my English...
I downloaded and included in the project latest commit bfa04b9. 
My source code:
```
require_once 'Services/OpenStreetMap.php';
  $config = [
    'adapter'         => 'HTTP_Request2_Adapter_Curl',
    'api_version'     => '0.6',
    'password'        => '*****',
    'server'          => 'https://my_local_osm_server',
    'User-Agent'      => 'Services_OpenStreetMap',
    'user'            => 'testuser',
    'ssl_verify_peer' => FALSE,
    'ssl_verify_host' => FALSE,
  ];

  $osm = new Services_OpenStreetMap($config);
```
I see that the constructor immediately makes a request **/api/capabilities**, and already at this point I get an error message:
```
Fatal error: Uncaught HTTP_Request2_ConnectionException: Curl error: SSL certificate problem: unable to get local issuer certificate in /var/www/html/osmapi/lib/HTTP/Request2/Adapter/Curl.php:155 Stack trace: #0 /var/www/html/osmapi/lib/HTTP/Request2/Adapter/Curl.php(184): HTTP_Request2_Adapter_Curl::wrapCurlError(Resource id #3) #1 /var/www/html/osmapi/lib/HTTP/Request2.php(946): HTTP_Request2_Adapter_Curl->sendRequest(Object(HTTP_Request2)) #2 /var/www/html/osmapi/lib/Services/OpenStreetMap/Transport/HTTP.php(160): HTTP_Request2->send() #3 /var/www/html/osmapi/lib/Services/OpenStreetMap/Config.php(377): Services_OpenStreetMap_Transport_HTTP->getResponse('https://s1.taga...') #4 /var/www/html/osmapi/lib/Services/OpenStreetMap/Config.php(266): Services_OpenStreetMap_Config->setServer('https://s1.taga...') #5 /var/www/html/osmapi/lib/Services/OpenStreetMap.php(94): Services_OpenStreetMap_Config->setValue(Array) #6 /var/www/html/osmapi/index.php(144): Services_OpenStreetMap->__construct(Array) #7 {main} Next Services_OpenS in /var/www/html/osmapi/lib/Services/OpenStreetMap/Config.php on line 379
```
I see that the Services_OpenStreetMap_Transport_HTTP :: getResponse method contains strings:
```
/* Issue 32 - SSL Config */
$request->setConfig('ssl_verify_peer', $config->getValue('ssl_verify_peer'));
$request->setConfig('ssl_verify_host', $config->getValue('ssl_verify_host'));
$request->setConfig('ssl_cafile', $config->getValue('ssl_cafile'));
$request->setConfig('ssl_local_cert', $config->getValue('ssl_local_cert'));
$request->setConfig('ssl_passphrase', $config->getValue('ssl_passphrase'));
```
Where $config created in the Services_OpenStreetMap_Transport_HTTP constructor as:
```
public function __construct()
    {
        $this->setConfig(new Services_OpenStreetMap_Config());
        $this->setRequest(new HTTP_Request2());
        $this->setLog(new Log_null(null, null));
    }
```
That is, as the default constructor with:
```
'ssl_verify_peer' => true,
'ssl_verify_host' => true,
'ssl_cafile' => null,
'ssl_local_cert' => null,
'ssl_passphrase' => null,
```
I can not avoid mistakes, because my settings do not affect the result.

**Comment by erkinsergey** [comment]
Yes, now everything works correctly. 
Thank you for your work.

**Comment by kenguest** [comment]
You're very welcome - am happy to get this bug fixed :-)
