### ISSUE TITLE
Add support for retrieving notes via the  /api/0.6/notes/search endpoint.

### ISSUE THREAD

**Issue by kenguest** [pear/Services_Openstreetmap#38]
It is currently only possible to retrieve notes via  bounding box - expand API/V06.php to also retrieve notes via the /notes/search endpoint which is described at https://wiki.openstreetmap.org/wiki/API_v0.6#Search_for_notes:_GET_.2Fapi.2F0.6.2Fnotes.2Fsearch

**Comment by LiamBailey** [comment]
I feel I would be able to make this happen for you - can I take it?

**Comment by kenguest** [comment]
Yes please. Just ensure coding standards and such are adhered to.

**Comment by kenguest** [comment]
Looks good - am closing this out as done.
