### ISSUE TITLE
Add checks that lenghts of keys and values on objects don't exceed 255 characters each

### ISSUE THREAD

**Issue by kenguest** [pear/Services_Openstreetmap#39]
a 255 character limit on keys and values for all object types should be imposed.

**Comment by LiamBailey** [comment]
Do you mean this limit to be on the xml or...?

**Comment by kenguest** [comment]
The limit should just be on the length of the string being used as the key and also on the length of the values, not the XML.

**Comment by LiamBailey** [comment]
Hi again @kenguest I added to my fork - an attempt at this one, let me know if it is on the right track

**Comment by kenguest** [comment]
This looks fine - thanks very much! If you want to add another PR you could add unit tests if you like ;-)
